(*) -down-> [--generate] "read arguments"
if "arguments valid" then
  -left-> [yes] "load model"
  --> "rotate model"
  --> "apply voxelifization algorithm"
  if "palette defined" then
    --> [yes] "apply palette"
    --> "saving stage" as a1
  else
    --> [no] a1
  endif
  --> ===SAVING===
  --> [--output-file given] "save voxelify format"
  --> ===SAVED===
  ===SAVING=== --> [--preview-image given] "build scene" as a2
  --> "render to PNG file"
  --> ===SAVED===
  ===SAVING=== --> [--preview-animation given] "build scene" as a3
  --> "render to GIF file"
  --> ===SAVED===

  --> (*)
else
  -right-> [no, error] (*)
endif
